//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace СoloringBookImageConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("СoloringBookImageConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предварительное размытие: .
        /// </summary>
        internal static string label_blur {
            get {
                return ResourceManager.GetString("label_blur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толщина линий: .
        /// </summary>
        internal static string label_line_thickness {
            get {
                return ResourceManager.GetString("label_line_thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальный размер области: .
        /// </summary>
        internal static string label_min_square {
            get {
                return ResourceManager.GetString("label_min_square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во цветов в палитре: .
        /// </summary>
        internal static string label_palette_size {
            get {
                return ResourceManager.GetString("label_palette_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коррекция синего: .
        /// </summary>
        internal static string label_pbcb {
            get {
                return ResourceManager.GetString("label_pbcb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коррекция зелёного: .
        /// </summary>
        internal static string label_pbcg {
            get {
                return ResourceManager.GetString("label_pbcg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коррекция красного:.
        /// </summary>
        internal static string label_pbcr {
            get {
                return ResourceManager.GetString("label_pbcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture files (*.png;*.jpg;*.bmp)|*.png;*.jpg;*.bmp.
        /// </summary>
        internal static string picture_format_filter {
            get {
                return ResourceManager.GetString("picture_format_filter", resourceCulture);
            }
        }
    }
}
